version: "3.4"

x-common-variables: &common-variables
  POSTGRES_USER: postgres

volumes:
  pg_sandbox_data:
  pg_development_data:

services:
  #duckdns:
  #  image: lscr.io/linuxserver/duckdns:latest
  #  container_name: duckdns
  #  network_mode: host #optional
  #  environment:
  #    - PUID=1000 #optional
  #    - PGID=1000 #optional
  #    - TZ=America/Los_Angeles #optional
  #    - SUBDOMAINS=sohagst
  #    - TOKEN=5b681ecf-3f19-4887-a932-fc1068983db2
  #    - UPDATE_IP=ipv4 #optional
  #    - LOG_FILE=true #optional
  #  volumes:
  #    - /path/to/duckdns/config:/config #optional
  #  restart: unless-stopped

  #db:
  #  image: postgres:11.2
  #  volumes:
  #    - ./database/init:/docker-entrypoint-initdb.d
  #    - "pg_${PLAID_ENV}_data:/var/lib/postgresql/data"
  #  ports:
  #    - 5432:5432
  #  environment: *common-variables

  server:
    build: ./server
    image: plaidinc/pattern-server:1.0.7
    ports:
      - 5001:5001
    environment:
      <<: *common-variables
      PLAID_CLIENT_ID:
      PLAID_SECRET_SANDBOX:
      PLAID_SECRET_DEVELOPMENT:
      PLAID_SANDBOX_REDIRECT_URI:
      PLAID_DEVELOPMENT_REDIRECT_URI:
      PLAID_ENV:
      PORT: 5001
      DB_PORT: 5432
      DB_HOST_NAME: sohagst.duckdns.org
      POSTGRES_PASSWORD:
    #depends_on:
    #  - db

  client:
    build: ./client
    image: plaidinc/pattern-client:1.0.7
    ports:
      - 3001:3001
    environment:
      REACT_APP_PLAID_ENV: ${PLAID_ENV}
      REACT_APP_SERVER_PORT: 5001
    depends_on:
      - server
